name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 5 * * *

jobs:
  ci:
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-apple-darwin
            host_os: macos-latest
          - target: x86_64-pc-windows-msvc
            host_os: windows-latest
    runs-on: ${{ matrix.host_os }}
    steps:
      - name: Build and test Rust package
        uses: rcook/rust-package-action@v0.0.2
        with:
          target: ${{ matrix.target }}
